# what do we want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: my-local-storage
  #storageClassName: cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20 Gi
---
# how do we want it implemented
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage
spec:
  storageClassName: my-local-storage
  capacity:
    storage: 20 Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/mnt/some/directory/structure/'
    type: DirectoryOrCreate
# ---
# apiVersion: storage.k8s.io/v1
# kind: StorageCclass
# metadata:
#   name: cloud-ssd
# provisioner: kubernetes.io/aws-ebs
# parameters:
#   type: gp2
